// <auto-generated />
namespace Plumbing_Tools_Store_Management_System_Main.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RegisterNewUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegisterNewUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202402240400192_RegisterNewUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
